FROM registry.access.redhat.com/ubi8/openjdk-17:1.14
MAINTAINER Redhat
COPY target/rest-service-complete-0.0.1-SNAPSHOT.jar /rest-service-complete-0.0.1.jar
ENTRYPOINT ["java","-jar","/rest-service-complete-0.0.1.jar"]
